Repository sideeffffect/sbt-decent-scala, pull requests merged in 2022-05, with the labels that each got.

#225 Update scalafmt-core to 3.5.2
  .scalafmt.conf
Labels: type: dependencies

#224 Update sbt-tpolecat to 0.3.1
  project/Dependencies.scala
  project/plugins.sbt
Labels: type: dependencies, type: breaking

#227 Scala 3: -Xmax-inlines:1024
  src/main/scala/com/github/sideeffffect/sbtdecentscala/DecentScalaPlugin.scala
Labels: mergify-merge

#229 Update scalafmt-core to 3.5.3
  .scalafmt.conf
Labels: type: dependencies
